"""Thin FastAPI layer over the research orchestrator.

Endpoints
---------
- GET  /                      service info + disclaimer
- POST /research              run a research request; returns run summary
- GET  /runs/{run_id}/memo    fetch the saved memo markdown
- GET  /runs/{run_id}/trace   fetch the JSONL tool-call trace

Run with:  uv run uvicorn api:app --reload
The API is a thin adapter: all logic lives in agents/. Educational/research
use only.
"""

from __future__ import annotations

import asyncio
from pathlib import Path

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

from agents.base import mode_label
from agents.orchestrator import ResearchOrchestrator
from core.config import OUTPUT_DIR
from core.trace import read_trace

app = FastAPI(
    title="Market Research Agents API",
    description=(
        "Multi-agent market research memo generator over authored MCP servers. "
        "For educational and research purposes only — not investment advice."
    ),
    version="0.1.0",
)

# One orchestrator per request keeps runs isolated (own trace, own servers).
# v1 keeps it simple and synchronous-with-await; a queue comes later.


class ResearchRequest(BaseModel):
    request: str
    transport: str = "stdio"  # or "inproc"


@app.get("/")
async def root() -> dict:
    return {
        "service": "market-research-agents",
        "model_mode": mode_label(),
        "disclaimer": "For educational and research purposes only. Not investment advice.",
        "endpoints": ["POST /research", "GET /runs/{run_id}/memo", "GET /runs/{run_id}/trace"],
    }


@app.post("/research")
async def run_research(body: ResearchRequest) -> dict:
    if not body.request.strip():
        raise HTTPException(status_code=422, detail="request must be non-empty")
    orch = ResearchOrchestrator(transport=body.transport)
    try:
        result = await orch.run(body.request)
    except Exception as exc:  # surface pipeline errors as HTTP 500 with detail
        raise HTTPException(status_code=500, detail=f"run failed: {exc}") from exc
    return {
        "run_id": orch.run_id,
        "output_path": result.output_path,
        "trace_path": str(orch.trace.path),
        "model_mode": result.model_mode,
        "verification_passed": result.verification.passed,
        "n_claims_checked": len(result.verification.claim_reports),
        "unresolved_flags": result.verification.unresolved_flags,
        "plan": result.plan.model_dump(),
        "memo_markdown": result.memo_markdown,
    }


def _run_dir(run_id: str) -> Path:
    # run ids are generated by new_run_id(); validate shape to prevent traversal.
    import re

    if not re.fullmatch(r"[0-9T]+-?[A-Za-z0-9\-]{4,40}", run_id) or ".." in run_id or "/" in run_id or "\\" in run_id:
        raise HTTPException(status_code=400, detail="invalid run_id")
    return Path(OUTPUT_DIR)


@app.get("/runs/{run_id}/memo")
async def get_memo(run_id: str) -> dict:
    path = _run_dir(run_id) / f"memo_{run_id}.md"
    if not path.exists():
        raise HTTPException(status_code=404, detail=f"no memo for run {run_id}")
    return {"run_id": run_id, "memo_markdown": path.read_text(encoding="utf-8")}


@app.get("/runs/{run_id}/trace")
async def get_trace(run_id: str) -> dict:
    from core.config import get_settings

    path = get_settings().data_dir / "traces" / f"{run_id}.jsonl"
    if not path.exists():
        raise HTTPException(status_code=404, detail=f"no trace for run {run_id}")
    return {"run_id": run_id, "events": read_trace(path)}
