"""Stage 5: writer agent — synthesize the memo with explicit numeric citations.

Live mode: Claude writes the memo and returns JSON {title, executive_summary,
body_markdown, claims}. The system prompt enforces the calibration rules:
every number must come from the provided metrics/no-data payload, weak
samples get hedged language, no recommendations.

Offline mode (or model failure): a deterministic memo builder renders the
same sections directly from the structured results. It is clearly labeled
mode="offline" and produces exactly the same numeric claims the verification
step will later check — so the offline path exercises the full pipeline.
"""

from __future__ import annotations

from agents.base import ask_structured
from agents.schemas import GatheredData, MemoDraft, QuantOutput, TaskPlan
from core.trace import TraceLogger


class WriterAgent:
    name = "writer_agent"

    def __init__(self, trace: TraceLogger | None = None) -> None:
        self.trace = trace

    async def write(self, plan: TaskPlan, gathered: GatheredData, quant: QuantOutput) -> MemoDraft:
        if _claude_available():
            try:
                draft = self._write_with_claude(plan, gathered, quant)
                self._trace(draft, mode="claude")
                return draft
            except Exception as exc:
                if self.trace:
                    self.trace.agent_step(self.name, "writer_fallback", reason=str(exc))
                draft = self._offline_memo(plan, gathered, quant, fallback_reason=str(exc))
                self._trace(draft, mode="offline_fallback")
                return draft
        draft = self._offline_memo(plan, gathered, quant, fallback_reason=None)
        self._trace(draft, mode="offline")
        return draft

    # ------------------------------------------------------------------
    # Live path
    # ------------------------------------------------------------------
    def _write_with_claude(self, plan: TaskPlan, gathered: GatheredData, quant: QuantOutput) -> MemoDraft:
        system = (
            "You write equity-sector research memos for an EDUCATIONAL tool. "
            "Hard rules: (1) every number you write must appear verbatim in the "
            "provided metrics or tool results — never invent or transform one; "
            "(2) use calibrated language and state sample sizes, e.g. 'positive "
            "but weak (0.05, n=30 days)'; (3) no buy/sell recommendations, no "
            "predictions, no certainty words like 'will' or 'proven'; (4) if "
            "data is missing say so plainly in Data Gaps; (5) cite metrics as "
            "[metric_name] next to each number. Return JSON: {title, "
            "executive_summary, body_markdown, claims} where claims is a list "
            "of the atomic factual statements you made (one sentence each, "
            "numbers included)."
        )
        prompt = (
            f"User request: {plan.request_summary!r}\n"
            f"Plan: {plan.model_dump_json()}\n\n"
            f"METRICS (the only numbers you may cite): {quant.model_dump_json()}\n\n"
            f"NO-DATA (report these honestly): {gathered.no_data}\n\n"
            f"FUNDAMENTALS: {_compact(gathered.fundamentals)}\n\n"
            f"NEWS: {_compact_news(gathered)}\n\n"
            "Write the memo. Sections: Executive Summary; Data Table (markdown "
            "table of the metrics with n and window); Key Findings (bullets "
            "with [metric] citations); Data Gaps; Risks & Limitations. End the "
            "body with the disclaimer: 'For educational and research purposes "
            "only. Not investment advice.'"
        )
        return ask_structured(prompt, MemoDraft, system=system)

    # ------------------------------------------------------------------
    # Offline path — deterministic, full pipeline still exercised
    # ------------------------------------------------------------------
    def _offline_memo(self, plan: TaskPlan, gathered: GatheredData, quant: QuantOutput, fallback_reason: str | None) -> MemoDraft:
        lines: list[str] = []
        mode_note = (
            f"\n> **Mode note:** writer fell back to the deterministic template "
            f"({fallback_reason})\n" if fallback_reason else
            "\n> **Mode note:** offline mode (no ANTHROPIC_API_KEY) — memo generated by "
            "the deterministic template, not Claude.\n"
        )
        title = f"Research memo: {plan.request_summary}"
        lines.append(f"# {title}\n")
        lines.append(mode_note)

        lines.append("## Executive summary\n")
        lines.append(_offline_summary(plan, quant, gathered))
        lines.append("")

        lines.append("## Data table\n")
        lines.append(_offline_table(quant))
        lines.append("")

        lines.append("## Key findings\n")
        claims = _offline_claims(plan, quant)
        for c in claims:
            lines.append(f"- {c}")
        lines.append("")

        lines.append("## News sentiment\n")
        lines.append(_offline_news(gathered))
        lines.append("")

        lines.append("## Data gaps\n")
        gaps = _offline_gaps(quant, gathered)
        if gaps:
            for g in gaps:
                lines.append(f"- {g}")
        else:
            lines.append("- None: all requested data was retrieved.")
        lines.append("")

        lines.append("## Risks & limitations\n")
        lines.append(
            "- Signals are descriptive statistics over the stated window; they are not forecasts.\n"
            "- Small samples make estimates noisy; treat magnitudes as indicative only.\n"
            "- Yahoo Finance data can be delayed or revised; news coverage is a sample, not a census.\n"
            "- No transaction costs, liquidity, or position sizing are considered.\n"
        )
        lines.append("\n---\n*For educational and research purposes only. Not investment advice.*")

        body = "\n".join(lines)
        return MemoDraft(title=title, executive_summary=_offline_summary(plan, quant, gathered), body_markdown=body, claims=claims)

    def _trace(self, draft: MemoDraft, mode: str) -> None:
        if self.trace:
            self.trace.agent_step(
                self.name, "memo_written", mode=mode,
                n_claims=len(draft.claims), title=draft.title,
            )


# --------------------------------------------------------------------------
# offline helpers
# --------------------------------------------------------------------------
def _fmt(v: float) -> str:
    return f"{v:.4g}"


def _offline_summary(plan: TaskPlan, quant: QuantOutput, gathered: GatheredData) -> str:
    if not quant.metrics:
        return (
            "No metrics could be computed: the data sources returned nothing usable. "
            "See Data Gaps for the honest details — no numbers are fabricated."
        )
    mom = [(k, m) for k, m in quant.metrics.items() if k.endswith("_momentum")]
    if mom:
        if len(mom) == 1:
            k, m = mom[0]
            s = (
                f"{k.split('_')[0]} momentum over the {m.get('window_days')}-day window is "
                f"{_fmt(m['value'])} (n={m.get('n_observations')} days) — a single descriptive "
                "estimate over the stated window, not a forecast."
            )
        else:
            best_k, best_m = max(mom, key=lambda kv: kv[1].get("value", 0.0))
            worst_k, worst_m = min(mom, key=lambda kv: kv[1].get("value", 0.0))
            s = (
                f"Across {len(mom)} momentum estimate(s) over a {plan.lookback_days}-day window, "
                f"{best_k.split('_')[0]} shows the strongest momentum ({_fmt(best_m['value'])}, "
                f"n={best_m.get('n_observations')} days) while {worst_k.split('_')[0]} shows the "
                f"weakest ({_fmt(worst_m['value'])}, n={worst_m.get('n_observations')} days). "
                "These are descriptive statistics over the stated window, not forecasts."
            )
        if gathered.no_data:
            s += f" Data gaps: {', '.join(gathered.no_data)} (no values fabricated)."
        return s
    return f"Computed {len(quant.metrics)} metric(s) for the request; see the data table."


def _offline_table(quant: QuantOutput) -> str:
    if not quant.metrics:
        return "_No metrics computed._"
    header = "| Metric | Value | n | Window (days) |\n|---|---|---|---|"
    rows = []
    for name, m in quant.metrics.items():
        rows.append(
            f"| {name} | {_fmt(m.get('value', float('nan')))} | {m.get('n_observations', 'n/a')} | {m.get('window_days', 'n/a')} |"
        )
    return "\n".join([header] + rows)


def _offline_claims(plan: TaskPlan, quant: QuantOutput) -> list[str]:
    claims: list[str] = []
    for name, m in quant.metrics.items():
        ticker, signal = name.rsplit("_", 1)
        v = m.get("value")
        n = m.get("n_observations")
        w = m.get("window_days")
        if signal == "momentum":
            direction = "positive" if v > 0 else "negative" if v < 0 else "flat"
            strength = "weak" if abs(v) < 0.05 else "moderate"
            claims.append(
                f"{ticker} momentum over the {w}-day window is {direction} but {strength} "
                f"({_fmt(v)}, n={n} days)."
            )
        elif signal == "volatility":
            claims.append(
                f"{ticker} annualized realized volatility over the {w}-day window is {_fmt(v)} "
                f"(n={n} days), computed from daily log returns."
            )
    return claims


def _offline_news(gathered: GatheredData) -> str:
    news = getattr(gathered, "news", None)
    if not news:
        return "_News not requested or not available in this run._"
    headlines = news.get("headlines") or {}
    if not headlines.get("ok"):
        return f"_No headlines found: {headlines.get('error', 'unknown')} _"
    r = headlines["result"]
    items = r.get("items", [])[:5]
    lines = [f"Source: {r.get('source_used')} · {r.get('item_count')} headlines in the last {r.get('window_days')} days."]
    for it in items:
        lines.append(f"- \"{it['title']}\" — {it.get('source')}")
    sent = news.get("sentiment")
    if sent and sent.get("ok"):
        sr = sent["result"]
        lines.append(
            f"Aggregate sentiment: {sr.get('label')} (score {_fmt(sr.get('score', 0.0))}, "
            f"confidence {sr.get('confidence')}, mode {sr.get('mode')}, n={sr.get('n_headlines')}). "
            f"{sr.get('reasoning', '')}"
        )
    elif sent:
        lines.append(f"Sentiment unavailable: {sent.get('error')}")
    return "\n".join(lines)


def _offline_gaps(quant: QuantOutput, gathered: GatheredData) -> list[str]:
    gaps = [f"{t}: {reason}" for t, reason in gathered.no_data.items()]
    gaps.extend(gathered.notes)
    gaps.extend(quant.notes)
    return gaps


def _compact(fundamentals: dict) -> str:
    out = {}
    for t, env in fundamentals.items():
        if env.get("ok"):
            out[t] = env["result"].get("fields", {})
    return out


def _compact_news(gathered: GatheredData) -> str:
    news = getattr(gathered, "news", None)
    if not news:
        return "none"
    headlines = news.get("headlines") or {}
    if not headlines.get("ok"):
        return {"status": "no_data", "error": headlines.get("error")}
    return {
        "source_used": headlines["result"].get("source_used"),
        "titles": [i["title"] for i in headlines["result"].get("items", [])],
        "sentiment": news.get("sentiment", {}).get("result") if news.get("sentiment") else None,
    }


def _claude_available() -> bool:
    from core import model as model_client

    return model_client.available()
